// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZhufVdf1UKo5MHKMvuNbIQOXg5RfIZ9s',
    appId: '1:829953581889:web:3beec9d834a77170e1f7c0',
    messagingSenderId: '829953581889',
    projectId: 'morocco2030',
    authDomain: 'morocco2030.firebaseapp.com',
    storageBucket: 'morocco2030.firebasestorage.app',
    measurementId: 'G-X65BWLPDN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtw2SgMIZjeYpy1DSHKJ7DxiaH_rXddrg',
    appId: '1:829953581889:android:e5629800abca968de1f7c0',
    messagingSenderId: '829953581889',
    projectId: 'morocco2030',
    storageBucket: 'morocco2030.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfi47R9mMOp6c-xM_nKKJhK5GEsjFZy0s',
    appId: '1:829953581889:ios:194fa30ee5d003e1e1f7c0',
    messagingSenderId: '829953581889',
    projectId: 'morocco2030',
    storageBucket: 'morocco2030.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfi47R9mMOp6c-xM_nKKJhK5GEsjFZy0s',
    appId: '1:829953581889:ios:194fa30ee5d003e1e1f7c0',
    messagingSenderId: '829953581889',
    projectId: 'morocco2030',
    storageBucket: 'morocco2030.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZhufVdf1UKo5MHKMvuNbIQOXg5RfIZ9s',
    appId: '1:829953581889:web:8dfa2fa4dc812bb7e1f7c0',
    messagingSenderId: '829953581889',
    projectId: 'morocco2030',
    authDomain: 'morocco2030.firebaseapp.com',
    storageBucket: 'morocco2030.firebasestorage.app',
    measurementId: 'G-H76G7PV8DN',
  );
}
